---
- hosts: localhost
  tasks:
   - name: Download 
     get_url: 
       url: https://exchange.nagios.org/components/com_mtree/attachment.php?link_id=3328&cf_id=24
       dest: /home/centos/check_open_files.pl
       mode: 0755
   
   - name: copy 
     copy: 
       src: /home/centos/check_open_files.pl
       dest: /tmp/check_open_files.pl
       mode: 0755

   - name: modifying the nagios plugins dir path 
     lineinfile:
       dest: /home/centos/check_open_files.pl
       regexp: '^use lib'
       line: 'use lib "/usr/local/nagios/libexec";'
