---
- hosts: localhost
  tasks: 
   - name: update the interval time 5 to 1 minute
     blockinfile: 
    #    insertafter: 'Local' 
        dest: /home/centos/template.cfg 
        state: absent
        block: |
          define service{
          name                            local-service           ; The name of this service template
          use                             generic-service         ; Inherit default values from the generic-service definition
          max_check_attempts              4                       ; Re-check the service up to 4 times in order to determine its final (hard) state
          normal_check_interval           5                       ; Check the service every 5 minute under normal conditions
          retry_check_interval            1                       ; Re-check the service every minute until a hard state can be determined
          register                        0                       ; DONT REGISTER THIS DEFINITION - ITS NOT A REAL SERVICE, JUST A TEMPLATE!
          }
     
     
